{% set name = "pyxem" %}
{% set version = "0.12.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ff3c34b798b34b64685c1af1c8dbe2a39c7d0d5aa53b1b7b110727140f7274a5


build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3
  run:
    - python >=3
    - scikit-image >=0.15.0,<0.17
    - matplotlib-base >=3.1.1
    - scikit-learn >=0.19
    - hyperspy-base ==1.5.2
    - diffsims >=0.3
    - lmfit >=0.9.12
    - ipywidgets
    - pyfai-base
    - numba

test:
  requires:
    - pytest>=5.0
    - pytest-cov>=2.8.1
    - coveralls>=1.10
    - coverage>=5.0
  imports:
    - pyxem
    - pyxem.utils
    - pyxem.detectors
    - pyxem.components
    - pyxem.generators
    - pyxem.signals
    - pyxem.libraries
    - pyxem.dummy_data
  commands:
    - pytest --pyargs pyxem

about:
  home: https://github.com/pyxem/pyxem
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: An open-source Python library for crystallographic diffraction microscopy
  doc_url: http://pyxem.github.io/pyxem-website/

extra:
  recipe-maintainers:
    - dnjohnstone
    - pc494
