{% set name = "pyxem" %}
{% set version = "0.11.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d9f4150fce107a9f5b906d575abad68f00f9f9531dc712c60aed391a5166221f


build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3
  run:
    - python >=3
    - diffsims >=0.2.3
    - hyperspy >=1.5.2
    - scikit-image ==0.16.2
    - matplotlib-base >=3.1.1
    - scikit-learn >=0.19
    - lmfit >=0.9.12
    - pyfai
    - numba

test:
  requires:
    - pytest
  imports:
    - pyxem
    - pyxem.utils
    - pyxem.detectors
    - pyxem.components
    - pyxem.generators
    - pyxem.signals
    - pyxem.libraries
  commands:
    - pytest --pyargs pyxem

about:
  home: https://github.com/pyxem/pyxem
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: An open-source Python library for crystallographic diffraction microscopy
  doc_url: http://pyxem.github.io/pyxem-website/

extra:
  recipe-maintainers:
    - dnjohnstone
    - pc494
