{% set name = "pyxem" %}
{% set version = "0.10.0" %}


package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8b2579bf8568e32a4ad69be2810b300431d69f6691ed473f5aadb9471c7bc3bf


build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python >=3
  run:
    - python >=3
    - diffsims
    - hyperspy >=1.5.2
    - scikit-image >=0.15
    - matplotlib >=3.1.1
    - scikit-learn >=0.19

test:
  requires:
    - pytest
  imports:
    - pyxem
    - pyxem.utils
    - pyxem.io_plugins
    - pyxem.components
    - pyxem.generators
    - pyxem.signals
    - pyxem.libraries
  commands:
    - pytest --pyargs pyxem

about:
  home: https://github.com/pyxem/pyxem
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: An open-source Python library for crystallographic diffraction microscopy
  doc_url: http://pyxem.github.io/pyxem-website/

extra:
  recipe-maintainers:
    - tschoonj
    - dnjohnstone
    - pc494
